server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.215.185.138/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: aimiaomiao
  redis:
    host: 114.215.185.138
    port: 6379
    password: aimiaomiao
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  data:
    elasticsearch:
      repositories:
        enabled: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:site/**/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 7200 #JWT的超期限时间(60*60*2)
  tokenHead: Bearer  #JWT负载中拿到开头